@startuml
actor Team
actor IFAAdministration
usecase ManageResources
usecase EnterTransaction
usecase ValidateAction
usecase ApproveAction
usecase NotifyParties
class ResourceManagementSystem

Team --> ManageResources
ManageResources --> EnterTransaction
EnterTransaction --> ValidateAction
ValidateAction --> ApproveAction
ApproveAction --> NotifyParties
NotifyParties --> ResourceManagementSystem
IFAAdministration --> ResourceManagementSystem
@enduml
